src/Entity/Booking.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PrePersist;
use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * 
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être supérieure à aujourd'hui !", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être plus éloignée que la date d'arrivée !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    
    public function isBookableDates()
    {
        $formatDay = function($day){
            return $day->format('Y-m-d');
        };
        // 1 - conaitre les dates impossibles
        $notAvailableDays = $this->ad->getNotAvailableDays();
        // 2 - comparer les dates aux dates impossibles
        $bookingDays = $this->getDays();

        // Tableau de chaines de caracter e des journees
        $days = array_map($formatDay, $bookingDays);
    
        // Tablezau de chaines des joursq pas dispo
        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if(array_search($day, $notAvailable) != false) return false;
        }

        return true;

    }

    /**
     * Récupération des jours de la réservation
     *
     * @return array tableau d'objets atetime des jours de la réservation
     */
    public function getDays()
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function ($dayTimestamp) {
            return new DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);
        return $days;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"email"},
 * message="Cet email est déjà présent, merci d'en utiliser un autre !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Il faut renseigner ici hein !!")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Il faut renseigner ici aussi hein !!")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ici aussi il faut renseigner !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Donnez une image là !!!")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * Attribut rajouté en public (flemme de faire les getter setters)
     * pour coller au formulaire qui necessite ce champ (c'est une bonne pratique)
     * 
     * Apparement, Symfony va pouvoir hasher le champ de confirmation ?
     * 
     * @Assert\EqualTo(propertyPath="hash", message="Les mots de passe ne correspondent pas !!!")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,minMessage="minErrorMessage il faut 10 minimum !",)
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100,minMessage="Il faut au moins 100 caractères ici tu sais !")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * Fonction crée dans le chap 8 pour se faciliter la vie lors de l'affichage du nom de l'utilisateur !
     * Ceci est utilisé dans ad/show.html.twig
     *
     */
    public function getFullName(){
        return "{$this->firstName} {$this->lastName}";
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Permet d'initialiser le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        // tranformation d'un tableau d'objets en tableau de chaines de caractere:
        // $roles = $this->userRoles->toArray();
        
        // dump($roles);
        
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();

        // on ajoute le role de base au tableau. Chaque utilisateur sur le site a le role de ROLE_USER
        $roles[] = "ROLE_USER";
        // dd($roles);


        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\User;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingFormType;
use App\Form\CommentFormType;
use Doctrine\ORM\EntityManager;
use Doctrine\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * 
     * @IsGranted("ROLE_USER")
     * 
     */
    public function book(Ad $ad, Request $request, EntityManagerInterface $manager): Response
    {
        $booking = new Booking();
        $user = new User();
        $user = $this->getUser();

        // création du form...
        $form = $this->createForm(BookingFormType::class, $booking);

        // gestion du form et de la requête générée...
        $form->handleRequest($request);

        // dd($user);
        // On check le form retourné...
        if ($form->isSubmitted() && $form->isValid()) {
            // Afin de récup des infos pour fournir notre ojet, on choppe le user connecté:
            $booking->setBooker($user)
                    ->setAd($ad);

            // si dates pas dispo : msg erreur, sinon on persiste !
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    "warning",
                    "Les dates sélectionnées ne sont pas disponibles !"
                );
            } else {

                // On rajoutera dans le prototype de la fonction : l'entity manager
                $manager->persist($booking);

                $manager->flush();

                return $this->redirectToRoute('booking_show', [
                    'id' => $booking->getId(),
                    'withAlert' => true // withAlert n'éatnt pas déclaré dans les routes, il s'affichera comme un get au bout de l'url: ?withAlert=true
                ]);
            }
        }



        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Afficher page de reservation
     * 
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     * @return Response
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $manager)
    {
        $comment = new Comment();

        $form = $this->createForm(CommentFormType::class, $comment);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());
            
            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                "Votre commentaire a bien été pris en compte !"
            );
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView(),
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce :
	{{ad.title}}
	!
{% endblock %}

{% block stylesheets %}

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous"/>


{% endblock %}

{% block body %}
	<div class="container">
		<h1>Réservez pour l'annonce :
			{{ad.title}}</h1>
		<p>Vous êtes sur le pint de réserver le bien de
			<strong>
				{{ad.author.fullName}}
			</strong>, dites nous tout, on s'occupe du reste !</p>
		{{ form_start(form) }}
		<div class="alert alert-light">
			<h2>Quelles sont les dates qui vous intéressent ?</h2>
			<div class="row">
				<div class="col">
					{{ form_row(form.startDate) }}
				</div>
				<div class="col">
					{{ form_row(form.endDate) }}
				</div>
			</div>
			<h4>Montant du séjour :
				<span id="amount">
					...
				</span>
				&euro;</h4>
			<span id="days">0</span>
			nuit(s) à
			{{ad.price}}
			/ nuit
			<h4 class="mt-3">Vous avez un commentaire ?</h4>
			{{ form_row(form.comment) }}
		</div>
		<h2>Vous avez terminé !</h2>
		<p>Vacances de rêve ? Hébergement pour le boulot ? Aqui, todo es possible.</p>
		<button type="submit" class="btn btn-success">Je réserve !</button>
		{{ form_end(form) }}
	</div>
{% endblock %}
{% block javascripts %}

	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>
	<script>
		$(document).ready(function () {
			$('#booking_form_startDate, #booking_form_endDate').datepicker({
				format: 'dd/mm/yyyy',
				datesDisabled: [{% for day in ad.notAvailableDays %}"{{ day.format('d/m/Y') }}",{% endfor %}],
				startDate: new Date() // pour que le calendar demarre ajd
			});
			// On colle un eventListenner aux champs date pour maj en temps réel du prix et nbre de nuits
			$('#booking_form_startDate, #booking_form_endDate').change(function(){
				calculateAmount()
			});
		});


		function calculateAmount(){
			// recup des dates
			// on va changer : 17/12/2020 en 2020-12-17 grâce à la regExp : (\d+)\/(\d+)\/(\d{4})
			// sinon ca ne marche pas, vu que les valeurs recuperees sont des dates fr...
			let endDate = new Date($('#booking_form_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
			let startDate = new Date($('#booking_form_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

			if(startDate && endDate && startDate < endDate){
				let DAY_TIME = 24*60*60*1000;
				let interval = endDate.getTime() - startDate.getTime();
				let days = interval / DAY_TIME;
				let amount = days * {{ ad.price }};

				$('#days').text(days);
				$('#amount').text(amount.toLocaleString('fr-FR'));
			} else {
				$('#days').text(0);
				amount = 0;
				$('#amount').text(amount.toLocaleString('fr-FR'));
			}
		}

	</script>

{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}
{% block title %}
	Réservation (n°{{booking.id}})
{% endblock %}
{% block body %}

	{% set ad = booking.ad %}
	{% set author = ad.author %}
	<div class="container">
		<h1>
			Votre réservation (n°{{booking.id}})
		</h1>


		{# Acceder a une requete depuis TWIG :  #}
		{# Ici, s'il y a ?withAlert=true à la fin de l'url, on aura un message en vert #}
		{% if app.request.query.get('withAlert') %}
			<div class="alert alert-success">
				<h4 class="alert-heading">Bravo !</h4>
				<p>Votre réservation auprès de
					<strong>
						<a href=" {{path('user_show', {'slug': author.slug})}} ">
							{{author.fullName}}
						</a>
					</strong>
					pour l'annonce
					<strong>
						<a href=" {{path('ads_show', {'slug': ad.slug})}} ">
							{{ad.title}}
						</a>
					</strong>
					a bien été prise en compte !</p>
			</div>
		{% endif %}

		<div class="row">
			<div class="col">
				<div class="alert alert-light">
					<h2>Détails</h2>

					<dl class="row">
						<dt class="col-md-4">Numéro</dt>
						<dd class="col-md-8">{{booking.id}}</dd>
						<dt class="col-md-4">Date d'arrivée</dt>
						<dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
						<dt class="col-md-4">Date de départ</dt>
						<dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
						<dt class="col-md-4">Nombre de nuits</dt>
						<dd class="col-md-8">{{booking.duration}}</dd>
						<dt class="col-md-4">Montant Total</dt>
						<dd class="col-md-8">{{booking.amount}}</dd>
						<dt class="col-md-4">Commentaire</dt>
						<dd class="col-md-8">{{booking.comment | default('Aucun commentaire')}}</dd>
					</dl>

					<hr>

					<h2 class="alert-heading">Votre hôte</h2>

					<div class="row mb-3">
						<div class="col-3">
							<img src=" {{author.picture}} " alt="Avatar de {{author.fullName}} " class="avatar avatar-medium">
						</div>
						<div class="col-9">
							<h4>
								<a href=" {{path('user_show', {'slug': author.slug})}} ">
									{{author.fullName}}
								</a>
							</h4>
							<span class="badge badge-primary">
								{{author.ads | length}}
								annonces</span>
						</div>
					</div>

					{{author.description | raw }}
					<a href=" {{path('user_show', {'slug': author.slug})}} " class="btn btn-primary">Plus d'infos sur
						{{author.firstName}}
					</a>
				</div>

				<div class="alert alert-light">
					<h2 class="alert-heading">
						Votre avis compte !
					</h2>
					{% if date() > date(booking.endDate) %}
						{# commentFromAuthor va AUTOMATIQUEMENT appeler getCommentFromAuthor #}
						{% set comment = booking.ad.commentFromAuthor(app.user) %}
						{% if comment is not null %}
							<blockquote>
								<i>
									{{comment.content}}
								</i>
							</blockquote>
							<strong>Note :
							</strong>
							{% include "partials/rating.html.twig" with {'rating': comment.rating} %}
						{% else %}

							{{ form_start(form) }}
							{{ form_widget(form) }}
							<button type="submit" class="btn btn-success">
								Confirmer!
							</button>
							{{ form_end(form) }}
						{% endif %}
					{% else %}
						<p>Vous ne pourrez pas noter cette annonce tant que votre voyage n'est pas complet.</p>
					{% endif %}

				</div>

			</div>
			<div class="col">
				<div class="alert alert-light">
					<h2 class="alert-heading">
						Votre Hébergement
					</h2>
					<h4>
						<a href=" {{path('ads_show', {'slug': ad.slug})}} ">
							{{ad.title}}
						</a>
					</h4>
					<img src=" {{ad.coverImage}} " alt="Image de {{ad.title}}" class="img-fluid">
					{{ad.content | raw}}

					<a href=" {{path('ads_show', {'slug': ad.slug})}} " class="btn btn-primary">Plus d'informations...</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}