src/Entity/Ad.php
<?php

namespace App\Entity;

use DateTime;
use App\Entity\User;
use Cocur\Slugify\Slugify;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PreUpdate;
use Doctrine\ORM\Mapping\PrePersist;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"title"},
 * message="Une autre annonce a déjà le même titre !"
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères !", maxMessage="Le titre ne peut pas faire plus de 255 caractères.")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="L'introduction doit faire plus de 20 caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="L'introduction doit faire plus de 100 caractères !")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(message = "The url '{{ value }}' is not a valid url")
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * Permet de connaitres les jours indisponibes pour une annonce
     *
     * @return array de dates
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            # calculer les jours entre start et end
            # on va utiliser la fonction range, ex monTab = range(10, 20, 5)  ---> monTab = [10, 15, 20] mais sur les ms d'une journée
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTImestamp(),
                24 * 60 * 60
            );

            $days = array_map(function ($dayTimestamp) {
                return new DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

    /**
     * Obtenir la note moyenne de l'annonce
     *
     * @return float
     */
    public function getAvgRatings()
    {
        # calculer la somme:
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0); // 0 est la valeur par défaut de la somme

        # Calculer la moyenne
        if (count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Permet de recup le commentaire d'un auteur sur une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"email"},
 * message="Cet email est déjà présent, merci d'en utiliser un autre !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Il faut renseigner ici hein !!")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Il faut renseigner ici aussi hein !!")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ici aussi il faut renseigner !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Donnez une image là !!!")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * Attribut rajouté en public (flemme de faire les getter setters)
     * pour coller au formulaire qui necessite ce champ (c'est une bonne pratique)
     * 
     * Apparement, Symfony va pouvoir hasher le champ de confirmation ?
     * 
     * @Assert\EqualTo(propertyPath="hash", message="Les mots de passe ne correspondent pas !!!")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,minMessage="minErrorMessage il faut 10 minimum !",)
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100,minMessage="Il faut au moins 100 caractères ici tu sais !")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * Fonction crée dans le chap 8 pour se faciliter la vie lors de l'affichage du nom de l'utilisateur !
     * Ceci est utilisé dans ad/show.html.twig
     *
     */
    public function getFullName(){
        return "{$this->firstName} {$this->lastName}";
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Permet d'initialiser le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        // tranformation d'un tableau d'objets en tableau de chaines de caractere:
        // $roles = $this->userRoles->toArray();
        
        // dump($roles);
        
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();

        // on ajoute le role de base au tableau. Chaque utilisateur sur le site a le role de ROLE_USER
        $roles[] = "ROLE_USER";
        // dd($roles);


        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/ad/_ad.html.twig
{# variable twig pour factoriser le code #}
{% set url = path('ads_show', {'slug': ad.slug}) %}
<div class="col-md-4">
	<div class="card bg-light mb-3">
		<div class="card-header text-center">
			{{ ad.rooms }}
			chambres,
			<strong>{{ ad.price }}
				&euro; / nuit</strong><br>
				{% if ad.comments|length > 0 %}
				{% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %}
					{% else %}
			<small>Pas encore noté</small>
				{% endif %}
		</div>
		<a href=" {{ url }} ">
			<img src=" {{ ad.coverImage}} " alt="image de l'appartement" style="height: 200px; width:100%; display: block;">
		</a>
		<div class="card-body">
			<h4 class="card-title">
				<a href=" {{ url}} ">
					{{ ad.title }}
				</a>
			</h4>
			<p class="card-text">
				{{ ad.introduction }}
			</p>
			<a href="{{ url}}" class="btn btn-secondary">En savoir plus !</a>

				{% if app.user and app.user == ad.author %}
				
			<a href="{{path('ads_edit', {'slug' : ad.slug})}}" class="btn btn-primary">
				Modifier l'annonce
			</a>

			{% endif %}

			
		</div>
	</div>
</div>

templates/ad/_collection.html.twig
{# On a mis ici la 'template' des éléments du formulaire relatif à la collection d'images #}

{% block _ad_form_images_widget %}
	<p>Ajoutez vos images !</p>
	{# la variable form dépend du bloc dans lequel elle est placée ! ici, ad_images #}
	{{ form_widget(form) }}
	{# un input SANS NAME n'est pas transmis au serveur !#}
	{# cet input permet de corriger un bug : 
			si on suppr le x ième form image et qu'on en remet un,
			les 2 ont le même indice !!! Ca craint.#}
	<input type="hidden" id="widgets-counter" value="0"> 
    <div class="form-group">

		<button type="button" id="add-image" class="btn btn-primary">
			Ajouter une image
		</button>
	</div>
{% endblock  %}


{% block _ad_form_images_entry_row %}
	{# la row contient le label, les erreurs, le widget et les aides#}
	{{form_widget(form)}}
{% endblock %}


{% block _ad_form_images_entry_widget %}
	<div class="form-group" id="block_{{id}}">
		{{ form_errors(form) }}
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col">
						{{ form_errors(form.url) }}
						{{ form_widget(form.url) }}
					</div>
					<div class="col">
						{{ form_errors(form.caption) }}
						{{ form_widget(form.caption) }}
					</div>
				</div>
			</div>
			<div class="col-2">
				<button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
			</div>
		</div>
	</div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Edition d'une annonce
{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
	<div class="container">
		<h1 class="h1">Modifier l'annonce :
			{{ ad.title}}
		</h1>

		{{ form_start(form) }}

		{{ form_widget(form) }}

		<button class="btn btn-primary">
			Enregistrer les modifications
		</button>

		{{ form_end(form) }}

	</div>
{% endblock %}


{% block javascripts %}
	<script src="/js/ad.js"></script>
{% endblock  %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Annonces
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="h1 my-3">Voici les annonces de nos hôtes !</h1>
		<div class="row">
			{% for ad in ads %}
			{% include "ad/_ad.html.twig" %}
			{% endfor %}
		</div>
	</div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}
{% block title %}
	Création d'une annonce
{% endblock %}

{#En lien avec l'affichage du form de la collection d'images:#}
{% block body %}
	<div class="container">
		<h1 class="h1">Créer une nouvelle annonce</h1>
		{% form_theme form 'ad/_collection.html.twig' %}

		{{ form_start(form) }}

		{{ form_widget(form) }}

		<button class="btn btn-primary">
			Créer la nouvelle annonce</button>

		{{ form_end(form) }}

	</div>
{% endblock %}

{# _NOM_widget permet de travailler seulement sur le champ ad_form_images 
(appelé images dans le AdFormType, le nom est visible dqns l'inspecteur) #}
{% block _ad_form_images_widget %}
	<p>Ajoutez vos images !</p>
	{# la variable form dépend du bloc dans lequel elle est placée ! ici, ad_images #}
	{{ form_widget(form) }}
	{# un input SANS NAME n'est pas transmis au serveur !#}
	{# cet input permet de corriger un bug : 
	si on suppr le x ième form image et qu'on en remet un,
	les 2 ont le même indice !!! Ca craint.#}
	<input type="hidden" id="widgets-counter" value="0">
	<div class="form-group">
		<button type="button" id="add-image" class="btn btn-primary">
			Ajouter une image
		</button>
	</div>
{% endblock  %}

{% block javascripts %}
	<script src="/js/ad.js"></script>
{% endblock  %}

templates/ad/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{ ad.title }}
{% endblock %}

{% block body %}
	<div class="ad-title" style="background-image: url( {{ ad.coverimage}} ) ">
		<div class="container">
			<h1 class="h1">
				{{ ad.title }}
			</h1>
			<p>{{ ad.introduction }}</p>
			<p class="h2">
				<strong>{{ ad.rooms }}
					chambres</strong>
				pour
				<strong>
					{{ ad.price }}&euro;
				</strong>
				par nuit.
			</p>
			<a href=" {{ path('booking_create', {'slug': ad.slug}) }} " class="btn btn-primary">Réserver</a>

			{% if app.user and app.user == ad.author %}

				<a href="{{path('ads_edit', {'slug' : ad.slug})}}" class="btn btn-primary">
					Modifier l'annonce
				</a>
				<a href="{{path('ads_delete', {'slug': ad.slug})}}" class="btn btn-danger" onclick="return confirm(`Êtes vous certqin de vouloir supprimer l'annonce : {{ad.title}} ?`)">Supprimer l'annonce</a>
			{% endif %}
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-8 mb-3">
				{{ ad.content | raw }}

				<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
					<div class="carousel-indicators">
						{% for img in ad.images %}

							<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to=" {{ loop.index0 }} " class="{% if loop.first %} active {% endif %}" aria-current="true" aria-label="Slide 1"></button>

						{% endfor %}
					</div>
					<div class="carousel-inner">
						{% for img in ad.images %}
							<div class="carousel-item {% if loop.first %} active {% endif %} ">
								<img src=" {{ img.url }} " class="d-block w-100" alt="first image">
								<div class="carousel-caption d-none d-md-block">
									<h5>
										{{ ad.title }}
									</h5>
									<p>
										{{ img.caption }}
									</p>
								</div>
							</div>
						{% endfor %}

					</div>
					<a class="carousel-control-prev" role="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</a>
					<a class="carousel-control-next" role="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</a>
				</div>

				<hr>
				{% if ad.comments | length > 0 %}
					<h2 class="mb-3">Commenaires de nos voyageurs :</h2>

					{# la note moyenne #}
					<div class="alert alert-info">
						<h4 class="alert-heading text-center">
						<div class="row align-items-center">
							<div class="col">
								Note globale donnée par nos voyageurs :
							</div>
							<div class="col">

								{% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %}
								<br>
								<small>(Calculée sur {{ad.comments | length}} avis)</small>

							</div>
						</div>
						</h4>
					</div>
					{% for comment in ad.comments %}
						<div class="bg-light rounded mb-3 py-3px-3">
							<strong>
								{{comment.author.firstName}}
							</strong>
							a dit :
							<blockquote>
								<i>
									{{comment.content}}

								</i>
							</blockquote>
							<strong>
								Note donnée	: 
							</strong>
							{# Pour que le block ait la vrible rating : #}
							{# {% set rating = comment.rating %} #}
							{# {% include "partial/rating.html.twig" %} #}
							{# Autre solution => en passant la variable dans un TABLEAU TWIG :  #}
							{# Ainsi, ce block RATING sera dispo partout, il suffit de lui passer une variable rating ! #}
						{% include "partials/rating.html.twig" with {'rating': comment.rating} %}
					</div>

					{% endfor %}

				{% else %}
					<h2>Cette annonce n'a pas encore reçu de commentaire...</h2>
				{% endif %}

			</div>
			<div
				class="col">
				{# on factorise ! #}
				{% set a = ad.author %}
				<div class="row mb-3 align-items-center">
					<div class="col-3">
						<a href=" {{ path('user_show', {'slug': a.slug})}} ">
							<img src=" {{ a.picture}} " class="avatar avatar-medium" alt="Avatar de {{ a.fullName }}">
						</a>
					</div>
					<div class="col">
						<a href=" {{ path('user_show', {'slug': a.slug})}} ">
							<h3>
								{{ a.fullName }}
							</h3>
						</a>
						<span class="badge badge-primary">
							{{ a.ads | length }}
							annonces</span>
					</div>
				</div>
				{{ a.description | raw}}
			</div>
		</div>
	</div>

{% endblock %}